export const imagesDataset = {
    "Cephalochordata": "https://inaturalist-open-data.s3.amazonaws.com/photos/1094470/large.jpg",
    "Urochordata": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Tunicate_komodo.jpg/1200px-Tunicate_komodo.jpg",
    "Minoxydea": "https://pensamentoverde.com.br/wp-content/uploads/2014/03/mg2-300x231.jpg",
    Petromyzontoidea: "https://static.mundoeducacao.uol.com.br/mundoeducacao/2022/01/1-lampreia.jpg",
    "Tubarão": "https://static.todamateria.com.br/upload/tu/ba/tubaraobranco-cke.jpg",
    Arraia: "https://conexaoplaneta.com.br/wp-content/uploads/2022/05/arraias-tiete-conexao-planeta.jpg",
    Quimera: "https://www.oceanario.pt/content/img/820x560/quimera_pedro_a._pina.jpg",
    Actinopterygii: "https://www.thoughtco.com/thmb/CQREYg_b_P0eaYUFx66XeWYTuXQ=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/157328516-56a5f6eb5f9b58b7d0df4f79.jpg",
    Dipnoi: "https://cdn.britannica.com/21/2221-004-E610423C/African-lungfish.jpg",
    Actinistia: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Latimeria_Paris.jpg/800px-Latimeria_Paris.jpg",
    Lissamphibia: "https://upload.wikimedia.org/wikipedia/commons/5/51/Amphibians.png",
    Monotremata: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Monotreme_collage.jpg/1200px-Monotreme_collage.jpg",
    Eutheria: "https://upload.wikimedia.org/wikipedia/commons/0/03/Eutheria.png",
    Marsupialia: "https://upload.wikimedia.org/wikipedia/commons/6/6a/Marsupialia.jpg",
    Lepidosauria: "https://upload.wikimedia.org/wikipedia/commons/8/8c/Lepidosauria_Diversity.jpg",
    Testudine: "https://upload.wikimedia.org/wikipedia/commons/2/21/Turtle_diversity.jpg",
    Crocodilia: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Crocodilia_montage.jpg/800px-Crocodilia_montage.jpg",
    Aves: "https://cdn.ambientes.ambientebrasil.com.br/wp-content/uploads/2020/12/mix_imagens_aves_2.jpg"
}